apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-deployment
  labels:
    app: amazon-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-app
  template:
    metadata:
      labels:
        app: amazon-app
    spec:
      containers:
      - name: amazon-app-container
        image: zeeshanr/amazon:v1
        ports:
        - containerPort: 80
